tags:
  [
  ]
bundles:
  [
    {
      frame: "mocap_bundle",
      tags: [
        {
          id: 14,
          corners: [
            [ 0.0940,  0.1065, 0.0],
            [ 0.0940,  0.0125, 0.0],
            [-0.0940,  0.0125, 0.0]
          ]
        },
        {
          id: 17,
          corners : [
            [ 0.0940, -0.0125, 0.0],
            [ 0.0940, -0.1065, 0.0],
            [-0.0940, -0.1065, 0.0]
          ]
        }
      ]
    }
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
